*** Variables ***
&{register}
...             text_register_name=com.example.vamsi.login:id/etRegName
...             text_register_phone_number=com.example.vamsi.login:id/etRegPhone
...             text_register_gmail=com.example.vamsi.login:id/etRegGmail
...             text_register_password=com.example.vamsi.login:id/etRegPassword
...             button_register=com.example.vamsi.login:id/btnRegLogin
...             text_toast_login_successful=xpath=//android.widget.Toast[@text="Registration successful"]
...             button_go_to_login=com.example.vamsi.login:id/btnGotoLogin
